name: LoginPlus
version: 2.5
authors: [CCBlueX]

main: tk.ccbluex.LoginPlus.LoginPlus
commands:
     login:
        aliases: [l]
     register:
        aliases: [r]
     changepassword:
        aliases: [cr]
     loginplus:
        aliases: [lp]